### ISSUE TITLE
Problems parsing complex HMDB names

### ISSUE THREAD

**Issue by gbaquer** [lifs-tools/goslin#34]
Some HMDB lipid names cannot be parsed.
I have implemented some patches in [@gbaquer/LipidParser](https://github.com/gbaquer/LipidParser). Happy to incorporate into goslin and test. Let me know.

**Issue 1: Functional groups**

- PG(20:4(8Z,11Z,14Z,17Z)**-2OH(5S,6R)**/22:6(4Z,7Z,10Z,13Z,16Z,19Z))
- PC(20:5(7Z,9Z,11E,13E,17Z)***-3OH(5,6,15)***/14:0)
- PS(18:2(10E,12Z)***+=O(9)***/18:1(9Z))

_Solution:_
Remove with REGEX
`x=re.sub('(-\w+\(\d+[ A-Za-z,\d]*\))|\+=\w\(\d+\)','',x)`

**Issue 2: Specific FA's**

- PA(P-16:0/***LTE4***)
- PE(***PGJ2***/20:5(5Z,8Z,11Z,14Z,17Z))
- PE(22:0/***5-iso PGF2VI***)

_Solution:_
Replace by the corresponding nomenclature. For example: PGJ2 -> 20:5
`for i in range(fa.shape[0]):
            x=re.sub(fa.name[i],fa.repname[i],x)`

**Comment by dominik-kopczynski** [comment]
Hi and sorry for the long response time. Thank you for the suggestions, I will incorporate them into goslin :-)

**Comment by dominik-kopczynski** [comment]
Hi @gbaquer,

I added the functionality into pygoslin, please checkout its master branch. Will add it now to the remaining instances. Please be aware that LTE4 cannot be described by the current shorthand nomenclature, thus this particular name won't work. But names like "PE(PGJ2/20:5(5Z,8Z,11Z,14Z,17Z))" is working now fine.

Cheers

**Comment by gbaquer** [comment]
Hi Dominik, thanks for incorporating the changes. Happy to be of help.

**Comment by dominik-kopczynski** [comment]
Thank you for your support. I added the support to all goslin implementations. Cheers
