### ISSUE TITLE
Handle LipidMaps sphingomyelin names

### ISSUE THREAD

**Issue by meowcat** [lifs-tools/goslin#9]
Currently, names like "SM 21:0;2O/21:1" are not successfully parsed.

**Comment by dominik-kopczynski** [comment]
Yuup, it is the recent changes in the nomenclature, which we do not cover yet. We will work on it. Thanks for spotting.

**Comment by nilshoffmann** [comment]
Cross linking this with the overarching issue #6

**Comment by nilshoffmann** [comment]
@meowcat SM d21:0/21:1 would be SM 21:0;O2/21:1 following the new nomenclature on SN level. This will be supported in version 2. Your example is unfortunately not compatible with the new nomenclature and would require your lipid name to be written as follows (assuming 5Z to be the double bond position of the FA): SM 21:0;2OH/21:1(5Z) on full structure level (potentially on complete, if no further stereo information (E/Z, R/S) is available).
